#!/bin/bash
ROFI_TEXT="󰴳 Wireguard control Menu"
typeset -A menu
menu=(
    [" Link UP"]="pkexec wg-quick up wg0"
    [" Link Down"]="pkexec wg-quick down wg0"
    [" Edit Config"]="kitty nvim /etc/wireguard/wg0.conf"
    ["󰑓 Reload"]="pkexec /etc/wireguard/wgl-reload.sh"
)
launcher_options=(-dmenu -i -lines "${#menu[@]}" -p "${ROFI_TEXT}" \
         "${ROFI_COLORS[@]}" "${ROFI_OPTIONS[@]}") 
launcher=(rofi "${launcher_options[@]}")
selection="$(printf '%s\n' "${!menu[@]}" | sort | "${launcher[@]}")"
if [[ -n $selection ]]
then
    exec ${menu[${selection}]}
fi
